# Generated by Django 5.0.4 on 2024-05-18 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_description_alter_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100)], verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_amount',
            field=models.BooleanField(default=False, verbose_name='Has Amount'),
        ),
    ]
