# Generated by Django 5.0.4 on 2024-05-23 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_has_quantity_remove_product_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.IntegerField(blank=True, help_text='For number of pcs in a set', null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100)], verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in mm', max_digits=6, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='This will add styling to highlight the product on the page', verbose_name='Is Featured'),
        ),
        migrations.AlterField(
            model_name='product',
            name='play_time',
            field=models.IntegerField(blank=True, choices=[(15, 'Mini'), (30, 'Short'), (60, 'Medium'), (120, 'Long'), (240, 'Epic'), (480, 'Legendary')], default=30, null=True, verbose_name='Play Time'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Hold "Crtl" while clicking select multiple tags', related_name='products', to='products.tag', verbose_name='Tags'),
        ),
    ]
